#!/usr/bin/env bash
## compile into executable hstone
gcc -o hstone hstone.c
## execute
./hstone
## generates hstone.js and hstone.wasm as well
emcc hstone.c -o hstone.html
## we'll provide our own HTML file
emcc hstonewa.c -o hstonewa.js
## new port number for emphasis
emrun --no_browser --port 7777 .
